const DEMO={admin:{password:'admin123',students:[
{name:'Aarav Reddy',studentId:'CSE23001',registrationNo:'JNTU23CSE001',admissionNo:'ADM-2023-001',department:'Computer Science and Engineering',program:'B.Tech',year:'4',semester:'7',section:'A',batch:'2023',dob:'2002-05-15',gender:'Male',email:'aarav.reddy@college.edu',phone:'+91-9876543210',address:'Hyderabad, Telangana',guardianName:'Reddy Kumar',guardianRelation:'Father',guardianPhone:'+91-9876543200',collegeName:'ENGINEERING COLLEGE',university:'JNTU Hyderabad',attendance:'82',cgpa:'8.5',backlogs:'0',credits:'120',portalUsername:'aarav.cse23001',portalStatus:'Active'},
{name:'Ananya Sharma',studentId:'ECE23014',registrationNo:'JNTU23ECE014',admissionNo:'ADM-2023-014',department:'Electronics and Communication Engineering',program:'B.Tech',year:'4',semester:'7',section:'B',batch:'2023',dob:'2002-08-22',gender:'Female',email:'ananya.sharma@college.edu',phone:'+91-9876543211',address:'Bangalore, Karnataka',guardianName:'Sharma Raj',guardianRelation:'Father',guardianPhone:'+91-9876543201',collegeName:'ENGINEERING COLLEGE',university:'JNTU Hyderabad',attendance:'78',cgpa:'7.8',backlogs:'0',credits:'120',portalUsername:'ananya.ece23014',portalStatus:'Active'},
{name:'Vikram Kumar',studentId:'MECH23031',registrationNo:'JNTU23ME031',admissionNo:'ADM-2023-031',department:'Mechanical Engineering',program:'B.Tech',year:'4',semester:'7',section:'A',batch:'2023',dob:'2002-03-10',gender:'Male',email:'vikram.kumar@college.edu',phone:'+91-9876543212',address:'Chennai, Tamil Nadu',guardianName:'Kumar Singh',guardianRelation:'Father',guardianPhone:'+91-9876543202',collegeName:'ENGINEERING COLLEGE',university:'JNTU Hyderabad',attendance:'72',cgpa:'7.2',backlogs:'1',credits:'110',portalUsername:'vikram.mech23031',portalStatus:'Active'}
]}};
const $=id=>document.getElementById(id);let currentUser=null,students=[],editingPhoto='';
function key(){return `srs_students_${currentUser}`};function users(){return JSON.parse(localStorage.getItem('srs_users')||JSON.stringify(DEMO))}function saveUsers(u){localStorage.setItem('srs_users',JSON.stringify(u))};function saveData(){localStorage.setItem(key(),JSON.stringify(students))}
function seed(){const u=users();if(!u.admin){u.admin=DEMO.admin;saveUsers(u)}}
function initials(n){return (n||'?').split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function loadData(){const raw=localStorage.getItem(key());if(raw===null){students=JSON.parse(JSON.stringify(users()[currentUser]?.students||[]));saveData()}else students=JSON.parse(raw)}function saveData(){localStorage.setItem(key(),JSON.stringify(students))}
function toast(m){$('toast').textContent=m;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function login(){currentUser=localStorage.getItem('srs_session');if(!currentUser)return false;loadData();$('loginScreen').classList.add('hidden');$('app').classList.remove('hidden');$('sideUser').textContent=currentUser;return true}
function logout(){localStorage.removeItem('srs_session');location.reload()}
function renderAll(){renderStats();renderStudents();renderAttendance();renderResults();renderActivity();renderAttention();$('darkToggle').checked=document.body.classList.contains('dark')}
function avg(field){return students.length?(students.reduce((a,s)=>a+Number(s[field]||0),0)/students.length):0}
function status(s){return Number(s.attendance)>=75&&Number(s.cgpa)>=7.5?'Good':Number(s.attendance)>=65||Number(s.cgpa)>=6.5?'Watch':'At Risk'}
function statusClass(v){return v==='Good'?'good':v==='Watch'?'warn':'danger'}
function renderStats(){$('statsGrid').innerHTML=[['Total Students',students.length,'Enrolled records'],['Avg Attendance',avg('attendance').toFixed(1)+'%','Across all students'],['Average CGPA',avg('cgpa').toFixed(2),'All students']].map(([t,v,d])=>`<div class="stat"><div class="stat-value">${v}</div><div class="stat-label">${t}</div><span class="stat-desc">${d}</span></div>`).join('')}
function renderStudents(){const q=($('searchInput')?.value||'').toLowerCase(),df=$('deptFilter')?.value||'all',yf=$('yearFilter')?.value||'all';const list=students.filter(s=>(!q||JSON.stringify(s).toLowerCase().includes(q))&&(df==='all'||s.department===df)&&(yf==='all'||s.year===yf));$('studentsList').innerHTML=list.length?list.map(s=>`<div class="student-card"><div class="student-card-header"><div class="student-avatar" title="${s.name}">${initials(s.name)}</div><div><h4>${s.name}</h4><p class="muted">${s.studentId}</p></div><div class="student-status ${statusClass(status(s))}">${status(s)}</div></div><div class="student-card-body"><p><strong>Department:</strong> ${s.department}</p><p><strong>Email:</strong> ${s.email}</p><p><strong>Attendance:</strong> ${s.attendance}%</p><p><strong>CGPA:</strong> ${s.cgpa}</p></div><div class="student-card-actions"><button onclick="previewStudent('${encodeURIComponent(s.studentId)}')" class="btn-action">👁️ Preview</button><button onclick="editStudent('${encodeURIComponent(s.studentId)}')" class="btn-action">✏️ Edit</button><button onclick="deleteStudent('${encodeURIComponent(s.studentId)}')" class="btn-action">🗑️ Delete</button></div></div>`).join(''):`<p class="empty-state">No students found. Add one to get started.</p>`;const depts=new Set(students.map(s=>s.department));$('deptFilter').innerHTML='<option value="all">All Departments</option>'+Array.from(depts).sort().map(d=>`<option value="${d}">${d}</option>`).join('')}
function renderAttendance(){$('attendanceStats').innerHTML=[['Average Attendance',avg('attendance').toFixed(1)+'%'],['Safe',students.filter(s=>Number(s.attendance)>=75).length],['Watch',students.filter(s=>Number(s.attendance)>=65&&Number(s.attendance)<75).length],['At Risk',students.filter(s=>Number(s.attendance)<65).length]].map(([l,v])=>`<div class="stat"><div class="stat-value">${v}</div><div class="stat-label">${l}</div></div>`).join('')}
function renderResults(){const bands=[['9+','9.0–10',students.filter(s=>Number(s.cgpa)>=9).length],['8–8.99','8.0–8.99',students.filter(s=>Number(s.cgpa)>=8&&Number(s.cgpa)<9).length],['7–7.99','7.0–7.99',students.filter(s=>Number(s.cgpa)>=7&&Number(s.cgpa)<8).length],['6–6.99','6.0–6.99',students.filter(s=>Number(s.cgpa)>=6&&Number(s.cgpa)<7).length],['<6','Below 6.0',students.filter(s=>Number(s.cgpa)<6).length]];$('resultsChart').innerHTML=bands.map(([b,r,c])=>`<div class="result-row"><span>${b}</span><div class="result-bar" style="width:${Math.max(c/students.length*100,5)}%"></div><span>${c}</span></div>`).join('')}
function renderActivity(){$('activityList').innerHTML=students.slice(-5).reverse().map(s=>`<div class="activity"><b>${s.name}</b> · ${s.studentId}<br><span class="muted">${s.department} · CGPA ${s.cgpa}</span></div>`).join('')}
function renderAttention(){$('attentionList').innerHTML=students.filter(s=>status(s)!=='Good').map(s=>`<div class="activity"><b>${s.name}</b> <span class="status ${statusClass(status(s))}">${status(s)}</span><br><span class="muted">${s.studentId} · Attendance ${s.attendance}%</span></div>`).join('')}
function switchSection(sec){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===sec));document.querySelectorAll('.page-section').forEach(s=>s.classList.toggle('active',s.id===sec));$('pageTitle').textContent=document.querySelector(`[data-section="${sec}"]`).textContent;sec==='students'&&renderStudents()}
function openModal(s=null){$('studentForm').reset();$('editId').value='';editingPhoto='';$('modalTitle').textContent=s?'Edit Student':'Add Student';if(s){Object.entries(s).forEach(([k,v])=>{const el=$('studentForm').elements[k];if(el)el.value=v})}$('modal').classList.add('show')}
function closeModal(){$('modal').classList.remove('show')}
function editStudent(id){const s=students.find(x=>x.studentId===decodeURIComponent(id));if(s)openModal(s)}
function deleteStudent(id){id=decodeURIComponent(id);if(confirm('Delete this student record?')){students=students.filter(s=>s.studentId!==id);saveData();renderAll();toast('Student record deleted')}}
function previewStudent(id){const studentId=decodeURIComponent(id);const s=students.find(x=>String(x.studentId)===String(studentId));if(!s){toast('Student record not found');return}sessionStorage.setItem('previewStudent',JSON.stringify(s));window.location.href='profile.html'}
function readForm(){const g=id=>$(id)?.value||'';return{name:g('name'),studentId:g('studentId'),registrationNo:g('registrationNo'),admissionNo:g('admissionNo'),department:g('department'),program:g('program'),year:g('year'),semester:g('semester'),section:g('section'),batch:g('batch'),dob:g('dob'),gender:g('gender'),email:g('email'),phone:g('phone'),address:g('address'),guardianName:g('guardianName'),guardianRelation:g('guardianRelation'),guardianPhone:g('guardianPhone'),collegeName:g('collegeName'),university:g('university'),attendance:g('attendanceInput'),cgpa:g('cgpa'),backlogs:g('backlogs'),credits:g('credits'),portalUsername:g('portalUsername'),portalStatus:g('portalStatus')}}
function saveStudent(e){e.preventDefault();const s=readForm(),old=$('editId').value;if(!s.studentId)return;const duplicate=students.some(x=>x.studentId===s.studentId&&x.studentId!==old);if(duplicate){toast('Student ID already exists');return}finishSave(s,old)}
function finishSave(s,old){if(old){const i=students.findIndex(x=>x.studentId===old);if(i!==-1)students[i]=s}else students.push(s);saveData();closeModal();switchSection('students');renderAll();toast(old?'Student updated':'Student added')}
function exportCSV(){const headers=['Name','Student ID','Registration No','Department','Program','Year','Semester','Section','Email','Phone','Guardian','Attendance','CGPA','Backlogs','Credits','Rank'];const rows=students.map(s=>[s.name,s.studentId,s.registrationNo,s.department,s.program,s.year,s.semester,s.section,s.email,s.phone,s.guardianName,s.attendance,s.cgpa,s.backlogs,s.credits,students.filter(x=>Number(x.cgpa)>Number(s.cgpa)).length+1]);const csv=[headers,...rows].map(r=>r.map(c=>`"${c}"`).join(',')).join('\n');const link=document.createElement('a');link.href='data:text/csv;charset=utf-8,'+encodeURIComponent(csv);link.download=`students_${new Date().toISOString().split('T')[0]}.csv`;link.click()}
function generateReport(type){const d=new Date().toLocaleString();let html=`<h3>${type==='attendance'?'Attendance Report':type==='performance'?'Performance Report':'Student Directory Report'}</h3><p>Generated on ${d}</p><table><tr><th>Name</th><th>ID</th><th>Department</th>`;if(type==='attendance')html+='<th>Attendance %</th>';else if(type==='performance')html+='<th>CGPA</th><th>Backlogs</th>';html+='</tr>';html+=students.map(s=>`<tr><td>${s.name}</td><td>${s.studentId}</td><td>${s.department}</td>`+(type==='attendance'?`<td>${s.attendance}%</td>`:type==='performance'?`<td>${s.cgpa}</td><td>${s.backlogs}</td>`:'')+'</tr>').join('');html+='</table>';const win=window.open('','Report');win.document.write(html);win.document.close()}
function init(){seed();$('loginForm').addEventListener('submit',e=>{e.preventDefault();const u=users(),name=$('loginUser').value.trim().toLowerCase(),pass=$('loginPass').value;if(u[name]?.password===pass){localStorage.setItem('srs_session',name);login();renderAll();toast('Welcome '+name)}else{$('authTitle').textContent='Access Denied';$('authSub').textContent='Invalid credentials. Try again.';setTimeout(()=>{$('authTitle').textContent='Sign in';$('authSub').textContent='Use your account to access your student record'},2000)}});$('showRegister').addEventListener('click',()=>{$('loginForm').classList.add('hidden');$('registerForm').classList.remove('hidden')});$('backLogin').addEventListener('click',()=>{$('loginForm').classList.remove('hidden');$('registerForm').classList.add('hidden')});$('registerForm').addEventListener('submit',e=>{e.preventDefault();const name=$('regUser').value.trim().toLowerCase(),pass=$('regPass').value,confirm=$('regConfirm').value;if(pass!==confirm){toast('Passwords do not match');return}const u=users();if(u[name]){toast('Username already exists');return}u[name]={password:pass,students:[]};saveUsers(u);toast('Account created! Please sign in.');$('loginForm').classList.remove('hidden');$('registerForm').classList.add('hidden');$('loginForm').reset()});$('studentForm')?.addEventListener('submit',saveStudent);$('cancelBtn')?.addEventListener('click',closeModal);$('searchInput')?.addEventListener('input',renderStudents);$('deptFilter')?.addEventListener('change',renderStudents);$('yearFilter')?.addEventListener('change',renderStudents);$('addStudentBtn')?.addEventListener('click',()=>openModal());$('exportBtn')?.addEventListener('click',exportCSV);$('attendanceReportBtn')?.addEventListener('click',()=>generateReport('attendance'));$('performanceReportBtn')?.addEventListener('click',()=>generateReport('performance'));$('directoryReportBtn')?.addEventListener('click',()=>generateReport('directory'));$('darkToggle')?.addEventListener('change',toggleTheme);document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',e=>switchSection(e.target.closest('.nav-item').dataset.section)));$('menuBtn')?.addEventListener('click',()=>$('sidebar').classList.toggle('mobile-open'));if(!login()){console.log('Not logged in')}}
function toggleTheme(){document.body.classList.toggle('dark');localStorage.setItem('srs_theme',document.body.classList.contains('dark')?'dark':'light');$('darkToggle').checked=document.body.classList.contains('dark')}
if(localStorage.getItem('srs_theme')==='dark')document.body.classList.add('dark');document.addEventListener('DOMContentLoaded',init);
